import 'package:flutter/material.dart';
import 'colors.dart';

const Size kMinSizeApp = Size(1400, 920);

const kFolderMedia = "C:\\media\\digicart";

const String logoEp = 'assets/icons/logoEptv.png';

final kAllowedAudiosExtensions = ['mp3', 'wav', 'aac', 'flac', 'ogg'];

const double kGainDefault = 80.00;

const String kHotkeyDefault = '';

final List<Color> kColorsDefault = [
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
  defaultColor,
];

final List<Color> kPredefinedColors = [
  defaultColor,
  Colors.black,
  Colors.red,
  Colors.green,
  Colors.blue,
  Colors.orange,
  Colors.purple,
  Colors.yellow,
  Colors.cyan,
  Colors.pink,
  Colors.teal,
  Colors.brown,
  Colors.indigo,
  Colors.lime,
  Colors.amber,
  Colors.deepOrange,
  Colors.lightBlue,
  Colors.lightGreen,
  Colors.deepPurple,
  Colors.grey,
  Colors.blueGrey,
  Colors.redAccent,
  Colors.greenAccent,
  Colors.blueAccent,
  Colors.pinkAccent,
  Colors.purpleAccent,
  Colors.tealAccent,
  Colors.amberAccent,
  Colors.cyanAccent,
  Colors.indigoAccent,
  Colors.limeAccent,
  Colors.deepOrangeAccent,
];

final List<double> kGains = [
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
];

final List<String> kMedias1 = [
  "C:/Users/pedro.reis/Videos/audio/1001 Nights PB - Rubinho R. (Rubinho R.) 2 05.mp3",
  "C:/Users/pedro.reis/Videos/audio/1001 Nights PB - Rubinho R. (Rubinho R.) 2 05.mp3",
  "C:/Users/pedro.reis/Videos/audio/1001 Nights PB - Rubinho R. (Rubinho R.) 2 05.mp3",
  "C:/Users/pedro.reis/Videos/audio/1001 Nights PB - Rubinho R. (Rubinho R.) 2 05.mp3",
  "C:/Users/pedro.reis/Videos/audio/1001 Nights PB - Rubinho R. (Rubinho R.) 2 05.mp3",
  "C:/Users/pedro.reis/Videos/audio/African Smiles - Edu Z (Edu Z) 1 35.mp3",
  "C:/Users/pedro.reis/Videos/audio/Almost a Cry -  Edu Z (Edu Z) 1 49.mp3",
  "C:/Users/pedro.reis/Videos/audio/Angel's Christmas Song - Rubinho R. (Rubinho R.) 2 04.mp3",
  "C:/Users/pedro.reis/Videos/audio/Apc Funk - TPA (TPA) 1 57.mp3",
  "C:/Users/pedro.reis/Videos/audio/Bay Mood - TPA (TPA) 1 57.mp3",
  "C:/Users/pedro.reis/Videos/audio/Bem-te-vi.mp3",
  "C:/Users/pedro.reis/Videos/audio/Bituca Jazz - TPA (TPA) 2 32.mp3",
  "C:/Users/pedro.reis/Videos/audio/Black Rio News ND - TPA (TPA) 1 21.mp3",
  "C:/Users/pedro.reis/Videos/audio/Black White.mp3",
  "C:/Users/pedro.reis/Videos/audio/Blowing in Jazz F 1.mp3",
  "C:/Users/pedro.reis/Videos/audio/BLOWING IN JAZZ.mp3",
  "C:/Users/pedro.reis/Videos/audio/Blue Chat ND - Bruno A (Bruno A) - 2 06.mp3",
  "C:/Users/pedro.reis/Videos/audio/BLUES EM VOCÊ F 1.mp3",
  "C:/Users/pedro.reis/Videos/audio/Bossa and Samba F 1.mp3",
  "C:/Users/pedro.reis/Videos/audio/Brest - TPA (TPA) 1 57.mp3",
  "C:/Users/pedro.reis/Videos/audio/Bright Ring - TPA (TPA) 2 52.mp3",
  "C:/Users/pedro.reis/Videos/audio/Brisa do Mar F 2.mp3",
  "C:/Users/pedro.reis/Videos/audio/By Night - F 1.mp3",
  "C:/Users/pedro.reis/Videos/audio/Chasing Victory - FUK (FUK)  02 24.mp3",
  "C:/Users/pedro.reis/Videos/audio/Child's Soul - TPA (TPA) 2 25.mp3",
  "C:/Users/pedro.reis/Videos/audio/Child's Soul ND - TPA (TPA) 2 27.mp3",
  "C:/Users/pedro.reis/Videos/audio/Christmas Ballad - Rubinho R. (Rubinho R.) 2 08.mp3",
  "C:/Users/pedro.reis/Videos/audio/Christmas is Coming - Rubinho R. (Rubinho R.) 2 08.mp3",
  "C:/Users/pedro.reis/Videos/audio/chuva e trovao.wav",
  "C:/Users/pedro.reis/Videos/audio/Classic Christmas - Rubinho R. (Rubinho R.) 1 59.mp3",
  "C:/Users/pedro.reis/Videos/audio/Lost In The Desert - FUK (FUK) 02 02.mp3",
  "C:/Users/pedro.reis/Videos/audio/Modern Country - Elias A. ( Elias A.) 02 32  .mp3",
  "C:/Users/pedro.reis/Videos/audio/Texas Road - Elias A. ( Elias A. ) 02 12 .mp3",
  "C:/Users/pedro.reis/Videos/audio/TRILHA_GLOBOREPORTER.wav",
  "C:/Users/pedro.reis/Videos/audio/UPM_BR680_2_El_Circo_Instrumental_Naylor_Tedesco_1161648.wav",
  "C:/Users/pedro.reis/Videos/audio/TRILHA_GLOBOREPORTER.wav",
  "C:/Users/pedro.reis/Videos/audio/UPM_BR680_2_El_Circo_Instrumental_Naylor_Tedesco_1161648.wav",
];

final List<String> kMedias2 = [
  "C:/Users/pedro.reis/Videos/audio/1001 Nights PB - Rubinho R. (Rubinho R.) 2 05.mp3",
  "C:/Users/pedro.reis/Videos/audio/A Day of Sadness - TPA (TPA) 2 45.mp3",
  "C:/Users/pedro.reis/Videos/audio/A Free Passion - TPA (TPA) 2 27.mp3",
  "C:/Users/pedro.reis/Videos/audio/A Night in Buenos Aires - TPA (TPA) 2 24.mp3",
  "C:/Users/pedro.reis/Videos/audio/African Smiles - Edu Z (Edu Z) 1 35.mp3",
  "C:/Users/pedro.reis/Videos/audio/Almost a Cry -  Edu Z (Edu Z) 1 49.mp3",
  "C:/Users/pedro.reis/Videos/audio/Angel's Christmas Song - Rubinho R. (Rubinho R.) 2 04.mp3",
  "C:/Users/pedro.reis/Videos/audio/Apc Funk - TPA (TPA) 1 57.mp3",
  "C:/Users/pedro.reis/Videos/audio/Bay Mood - TPA (TPA) 1 57.mp3",
  "C:/Users/pedro.reis/Videos/audio/Bem-te-vi.mp3",
  "C:/Users/pedro.reis/Videos/audio/Bituca Jazz - TPA (TPA) 2 32.mp3",
  "C:/Users/pedro.reis/Videos/audio/Black Rio News ND - TPA (TPA) 1 21.mp3",
  "C:/Users/pedro.reis/Videos/audio/Black White.mp3",
  "C:/Users/pedro.reis/Videos/audio/Blowing in Jazz F 1.mp3",
  "C:/Users/pedro.reis/Videos/audio/BLOWING IN JAZZ.mp3",
  "C:/Users/pedro.reis/Videos/audio/Blue Chat ND - Bruno A (Bruno A) - 2 06.mp3",
  "C:/Users/pedro.reis/Videos/audio/BLUES EM VOCÊ F 1.mp3",
  "C:/Users/pedro.reis/Videos/audio/Bossa and Samba F 1.mp3",
  "C:/Users/pedro.reis/Videos/audio/Brest - TPA (TPA) 1 57.mp3",
  "C:/Users/pedro.reis/Videos/audio/Bright Ring - TPA (TPA) 2 52.mp3",
  "C:/Users/pedro.reis/Videos/audio/Brisa do Mar F 2.mp3",
  "C:/Users/pedro.reis/Videos/audio/By Night - F 1.mp3",
  "C:/Users/pedro.reis/Videos/audio/Chasing Victory - FUK (FUK)  02 24.mp3",
  "C:/Users/pedro.reis/Videos/audio/Child's Soul - TPA (TPA) 2 25.mp3",
  "C:/Users/pedro.reis/Videos/audio/Child's Soul ND - TPA (TPA) 2 27.mp3",
  "C:/Users/pedro.reis/Videos/audio/Christmas Ballad - Rubinho R. (Rubinho R.) 2 08.mp3",
  "C:/Users/pedro.reis/Videos/audio/Christmas is Coming - Rubinho R. (Rubinho R.) 2 08.mp3",
  "C:/Users/pedro.reis/Videos/audio/chuva e trovao.wav",
  "C:/Users/pedro.reis/Videos/audio/Classic Christmas - Rubinho R. (Rubinho R.) 1 59.mp3",
  "C:/Users/pedro.reis/Videos/audio/Lost In The Desert - FUK (FUK) 02 02.mp3",
  "C:/Users/pedro.reis/Videos/audio/Modern Country - Elias A. ( Elias A.) 02 32  .mp3",
  "C:/Users/pedro.reis/Videos/audio/Texas Road - Elias A. ( Elias A. ) 02 12 .mp3",
  "C:/Users/pedro.reis/Videos/audio/TRILHA_GLOBOREPORTER.wav",
  "C:/Users/pedro.reis/Videos/audio/UPM_BR680_2_El_Circo_Instrumental_Naylor_Tedesco_1161648.wav",
  "C:/Users/pedro.reis/Videos/audio/TRILHA_GLOBOREPORTER.wav",
  "C:/Users/pedro.reis/Videos/audio/UPM_BR680_2_El_Circo_Instrumental_Naylor_Tedesco_1161648.wav",
];
